blogapp/urls.py
from django.urls import path
from .views import *

app_name = "blogapp"
urlpatterns = [
    path('', ClientHomeView.as_view(), name="home"),
    path('contact/', ClientContactView.as_view(), name="contact"),
    path('about/', ClientAboutView.as_view(), name="about"),
    path('sunil/', ClientSunilView.as_view(), name='sunil'),
    path('dipak/', ClientDipakView.as_view(), name='dipak'),
    path('cosmos/', ClientCosmosView.as_view(), name='cosmos'),
    path('blogs/<int:pk>/', ClientBlogDetailView.as_view(), name='blogdetail'),
    path('notices/', ClientNoticeListView.as_view(), name='noticelist'),
    path('notices/<int:pk>/', ClientNoticeDetailView.as_view(),
         name='noticedetail'),



    path('categories/<int:pk>/', ClientCategoryDetailView.as_view(),
         name='categorydetail'),
    path('books/<int:pk>/', ClientBookDetailView.as_view(),
         name='bookdetail'),



    path('blog-admin/', AdminHomeView.as_view(), name='adminhome'),
    path('blog-admin/login/', AdminLoginView.as_view(), name='adminlogin'),
    path('blog-admin/logout/', AdminLogoutView.as_view(), name='adminlogout'),


    path('blog-admin/messgaes/', AdminMessageListView.as_view(),
         name='adminmessagelist'),
    path('blog-admin/messages/<int:pk>/', AdminMessageDetailView.as_view(),
         name='adminmessagedetail'),


    # blog crud
    path("blog-admin/blogs/",
         AdminBlogListView.as_view(), name='adminbloglist'),
    path("blog-admin/blogs/create/",
         AdminBlogCreateView.as_view(), name='adminblogcreate'),
    path("blog-admin/blogs/<int:pk>/update/",
         AdminBlogUpdateView.as_view(), name='adminblogupdate'),
    path("blog-admin/blogs/<int:pk>/delete/",
         AdminBlogDeleteView.as_view(), name='adminblogdelete'),


    # notice crud
    path('blog-admin/notices/', AdminNoticeListView.as_view(),
         name='adminnoticelist'),
    path("blog-admin/notice/create/",
         AdminNoticeCreateView.as_view(), name='adminnoticecreate'),
    path("blog-admin/notices/<int:pk>/update/",
         AdminNoticeUpdateView.as_view(), name='adminnoticeupdate'),
    path("blog-admin/notices/<int:pk>/delete/",
         AdminNoticeDeleteView.as_view(), name='adminnoticedelete'),



    path('blog-admin/books/', AdminBookListView.as_view(),
         name='adminbooklist'),
    path('blog-admin/categories/', AdminCategoryListView.as_view(),
         name='admincategorylist'),

]

blogproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blogapp.urls')),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/clienttemplates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<title></title>

	<link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
  <link rel="stylesheet" type="text/css" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css">
</head>
<body class="container">

	<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = 'https://connect.facebook.net/en_US/sdk.js#xfbml=1&version=v3.0';
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>


<ul>
  	<li><a id="nava" href="{% url 'blogapp:home' %}">HOME</a></li>
  	<li><a id="nava" href="{% url 'blogapp:contact' %}">CONTACT</a></li>
  	<li><a id="nava" href="{% url 'blogapp:about' %}">ABOUT</a></li>
  	<li><a id="nava" href="{% url 'blogapp:cosmos' %}">COSMOS</a></li>
    <li><a id="nava" href="{% url 'blogapp:noticelist' %}">NOTICE</a></li>


</ul>
	
	{% block content %}

	{% endblock %}

<br>
<br>

</body>
</html>

templates/clienttemplates/clientabout.html
{% extends 'clienttemplates/base.html' %}



{% block sunil %}

<h3>hello this is about page</h3>
{% endblock %}

templates/clienttemplates/clientblogdetail.html
{% extends 'clienttemplates/base.html' %}



{% block content %}

<h3 id="blog-title">{{blog.title}}</h3><hr>
<p>Posted On: {{blog.date}}</p>
<br>
<img src="{{blog.image.url}}" width="500">
<p>{{blog.content}}</p>
<p>{{blog.author}}</p>
<div class="fb-share-button" data-href="{{request.build_absolute_uri}}" data-layout="button_count" data-size="small" data-mobile-iframe="true"><a target="_blank" href="{{request.build_absolute_uri}}" class="fb-xfbml-parse-ignore">Share</a></div>

<br>

<div class="fb-comments" data-href="https://developers.facebook.com/docs/plugins/comments#configlkmjlkkl" data-numposts="5"></div>

{% endblock %}

templates/clienttemplates/clientbookdetail.html
{% extends 'clienttemplates/base.html' %}


{% block content %}

<div class="row">
	<div class="col-md-8">
		
	
		<h3>{{book.name}}</h3>
		<p>{{book.about}}</p>
		<h5>{{book.writer}}</h5>
		<img src="{{book.image.url}}" class="img-thumbnail">
		<h5>Category: {{book.category.title}}</h5>
		

	</div>
	<div class="col-md-4">
		<h3><u>Related Books</u></h3>
		{% for book in book.category.books.all %}
		<li><a href="{% url 'blogapp:bookdetail' book.id %}">{{book.name}}</a></li><br>
		{% endfor %}
		

	</div>
</div>




{% endblock %}

templates/clienttemplates/clientcategorydetail.html
{% extends 'clienttemplates/base.html' %}



{% block content %}

<h3 id="welcome">Welcome to Sunil Thapa jr. Website.</h3>


<div class="row">
	<div class="col-md-8">
		
		<u><h3>{{category.title}}</h3></u>
		<img src="{{category.image.url}}" class="img-responsive img-thumbnail">
		<p>{{category.about}}</p>

		<h4>All books related to {{category.title}}</h4>
		{% for book in category.books.all %}
		<li><a href="{% url 'blogapp:bookdetail' book.id %}">{{book.name}}</a></li><br>
		{% endfor %}

		
	</div>
	<div class="col-md-4">
		
		This is side bar



	</div>
</div>

{% endblock %}

templates/clienttemplates/clientcontact.html
{% extends 'clienttemplates/base.html' %}



{% block content %}

<h3>Please contact us through the form below. </h3>

<form method="POST">
	{% csrf_token %}
	{{form.as_p}}
<button>Submit</button>
</form>
{% endblock %}

templates/clienttemplates/clientcosmos.html
{% extends 'clienttemplates/base.html' %}



{% block content %}

<h3>hello this is cosmos page</h3>
{% endblock %}

templates/clienttemplates/clienthome.html
{% extends 'clienttemplates/base.html' %}



{% block content %}

<h3 id="welcome">Welcome to Sunil Thapa jr. Website.</h3>


<div class="row">
	<div class="col-md-8">
		



		{% for blog in bloglist %}

		<h3>{{blog.title}} ({{blog.author}})</h3>
		<p>{{blog.content|truncatechars:"25"}}
		<a href="{% url 'blogapp:blogdetail' blog.id %}">Read more..</a>
		</p>


		{% endfor  %}
	</div>
	<div class="col-md-4">
		
		<h3>All Notices</h3>
		{% for notice in notices %}

		<h6><a href="{% url 'blogapp:noticedetail' notice.id %}">{{notice.title}}</a></h6>
		{% endfor %}


		<h3>All Categories</h3>

		{% for category in categories %}
		<h6><a href="{% url 'blogapp:categorydetail' category.id %}">{{category.title}}</a></h6>
		<img src="{{category.image.url}}" width="100">
		{% endfor %}

		<hr>
		<h3>All Books</h3>

		{% for book in books %}
		<h6><a href="{% url 'blogapp:bookdetail' book.id %}">{{book.name}} ({{book.category.title}})</a></h6>
		<img src="{{book.image.url}}" width="100">
		{% endfor %}


	</div>
</div>

{% endblock %}

templates/clienttemplates/clientnoticedetail.html
{% extends 'clienttemplates/base.html' %}



{%  block content %}

<h3>{{notice.title}}</h3>
<a href="{% url 'blogapp:noticeupdate' notice.id %}">Edit This Post</a>
<a href="{% url 'blogapp:noticedelete' notice.id %}">Delete This Post</a>
<p>Date: {{notice.date}}</p>
<p>{{notice.content}}</p>
<img src="{{notice.image.url}}">

{% endblock %}

templates/clienttemplates/clientnoticelist.html
{% extends 'clienttemplates/base.html' %}

{% block content %}
<style>
table {
    border-collapse: collapse;
    width: 100%;
}

th, td {
    text-align: left;
    padding: 8px;
}

tr:nth-child(even){background-color: #f2f2f2}

th {
    background-color: #4CAF50;
    color: white;
}
</style>
</head>
<body>

<h2>Notice </h2>

<table>
  <tr>
    <th>SN</th>
    <th>title</th>
    <th>content</th>
    <th>date</th>
  </tr>
  {% for a in noticelist %}
  <tr>
    <td>{{forloop.counter}}</td>
    <td><a href="{% url 'blogapp:noticedetail' a.id %}">{{a.title}}</a></td>
    <td><a href="{% url 'blogapp:noticedetail' a.id %}">{{a.content|truncatechars:'30'}}</a></td>
    <td>{{a.date|date}}</td>
  </tr>
  {% endfor %}
  
</table>
{% endblock %}