blogapp/urls.py
from django.urls import path
from .views import *

app_name = "blogapp"
urlpatterns = [
    path('', ClientHomeView.as_view(), name="home"),
    path('contact/', ClientContactView.as_view(), name="contact"),
    path('about/', ClientAboutView.as_view(), name="about"),
    path('sunil/', ClientSunilView.as_view(), name='sunil'),
    path('dipak/', ClientDipakView.as_view(), name='dipak'),
    path('cosmos/', ClientCosmosView.as_view(), name='cosmos'),
    path('blogs/<int:pk>/', ClientBlogDetailView.as_view(), name='blogdetail'),
    path('notices/', ClientNoticeListView.as_view(), name='noticelist'),
    path('notices/<int:pk>/', ClientNoticeDetailView.as_view(),
         name='noticedetail'),



    path('categories/<int:pk>/', ClientCategoryDetailView.as_view(),
         name='categorydetail'),
    path('books/<int:pk>/', ClientBookDetailView.as_view(),
         name='bookdetail'),



    path('blog-admin/', AdminHomeView.as_view(), name='adminhome'),
    path('blog-admin/login/', AdminLoginView.as_view(), name='adminlogin'),
    path('blog-admin/logout/', AdminLogoutView.as_view(), name='adminlogout'),


    path('blog-admin/messgaes/', AdminMessageListView.as_view(),
         name='adminmessagelist'),
    path('blog-admin/messages/<int:pk>/', AdminMessageDetailView.as_view(),
         name='adminmessagedetail'),


    # blog crud
    path("blog-admin/blogs/",
         AdminBlogListView.as_view(), name='adminbloglist'),
    path("blog-admin/blogs/create/",
         AdminBlogCreateView.as_view(), name='adminblogcreate'),
    path("blog-admin/blogs/<int:pk>/update/",
         AdminBlogUpdateView.as_view(), name='adminblogupdate'),
    path("blog-admin/blogs/<int:pk>/delete/",
         AdminBlogDeleteView.as_view(), name='adminblogdelete'),


    # notice crud
    path('blog-admin/notices/', AdminNoticeListView.as_view(),
         name='adminnoticelist'),
    path("blog-admin/notice/create/",
         AdminNoticeCreateView.as_view(), name='adminnoticecreate'),
    path("blog-admin/notices/<int:pk>/update/",
         AdminNoticeUpdateView.as_view(), name='adminnoticeupdate'),
    path("blog-admin/notices/<int:pk>/delete/",
         AdminNoticeDeleteView.as_view(), name='adminnoticedelete'),



    path('blog-admin/books/', AdminBookListView.as_view(),
         name='adminbooklist'),
    path('blog-admin/categories/', AdminCategoryListView.as_view(),
         name='admincategorylist'),

]

blogproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blogapp.urls')),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/admintemplates/adminblogcreate.html
{% extends 'admintemplates/base.html' %}


{% block content %}

<form method="POST" enctype="multipart/form-data">
	{% csrf_token %}
	{{form.as_p}}
	<button>Submit</button>
	
</form>

{% endblock %}

templates/admintemplates/adminblogdelete.html
{% extends 'admintemplates/base.html' %}



{% block content %}
<form method="POST" action="{% url 'blogapp:adminblogdelete' object.id %}">
	{% csrf_token %}
	<button>Confirm Delete?</button>
</form>
<a href="{% url 'blogapp:adminblogupdate' object.id %}">Cancel</a>

{% endblock %}

templates/admintemplates/adminbloglist.html
{% extends 'admintemplates/base.html' %}

{% block content %}
<style>
table {
    border-collapse: collapse;
    width: 100%;
}

th, td {
    text-align: left;
    padding: 8px;
}

tr:nth-child(even){background-color: #f2f2f2}

th {
    background-color: #4CAF50;
    color: white;
}
</style>
</head>
<body>

<h2>Blog <a href="{% url 'blogapp:adminblogcreate' %}"> Create New Blog</a></h2>

<table>
  <tr>
    <th>SN</th>
    <th>Title</th>
    <th>Content</th>
    <th>Author</th>
    <th>Date</th>
    <th>Edit Blog</th>
    <th>Delete Blog</th>
  </tr>
  {% for blog in bloglist %}
  <tr>
    <td>{{forloop.counter}}</td>
    <td>{{blog.title}}</td>
    <td>{{blog.content|truncatechars:'30'}}</td>
    <td>{{blog.author}}</td>
    <td>{{blog.date|date}}</td>
    <td><a href="{% url 'blogapp:adminblogupdate' blog.id %}"><button>Edit</button></a></td>
    <td><a href="{% url 'blogapp:adminblogdelete' blog.id %}"><button>Delete</button></a></td>
  </tr>
  {% endfor %}
  
</table>
{% endblock %}

templates/admintemplates/adminbookcreate.html
{% extends 'admintemplates/base.html' %}




{% block content %}

<form method="POST" enctype="multipart/form-data">
  {% csrf_token %}
  {{form.as_p}}
  <button>Submit</button>
  
</form>


{% endblock %}

templates/admintemplates/adminbookdetail.html
{% extends 'admintemplates/base.html' %}


{% block content %}

<div class="row">
	<div class="col-md-8">
		
	
		<h3>{{book.name}}</h3>
		<p>{{book.about}}</p>
		<h5>{{book.writer}}</h5>
		<img src="{{book.image.url}}" class="img-thumbnail">
		<h5>Category: {{book.category.title}}</h5>
		

	</div>
	<div class="col-md-4">
		<h3><u>Related Books</u></h3>
		{% for book in book.category.books.all %}
		<li><a href="{% url 'blogapp:adminbookdetail' book.id %}">{{book.name}}</a></li><br>
		{% endfor %}
		

	</div>
</div>




{% endblock %}

templates/admintemplates/adminbooklist.html
{% extends 'admintemplates/base.html' %}

{% block content %}
<style>
table {
    border-collapse: collapse;
    width: 100%;
}

th, td {
    text-align: left;
    padding: 8px;
}

tr:nth-child(even){background-color: #f2f2f2}

th {
    background-color: #4CAF50;
    color: white;
}
</style>
</head>
<body>

<table>
  <tr>
    <th>SN</th>
    <th>Name</th>
    <th>About</th>
    <th>Category</th>
    <th>Writer</th>
  </tr>
  {% for a in adminbooklist %}
  <tr>
    <td>{{forloop.counter}}</td>
    <td>{{a.name}}</td>
    <td>{{a.about|truncatechars:'30'}}</td>
    <td>{{a.category}}</td>
    <td>{{a.writer}}</td>
  </tr>
  {% endfor %}
  
</table>
{% endblock %}

templates/admintemplates/adminhome.html
{% extends 'admintemplates/base.html' %}
	


{% block content %}
	<h3>THis is admin panel </h3>
{% endblock %}

	

templates/admintemplates/adminlogin.html
<!DOCTYPE html>
<html>
<head>
	<title></title>
</head>
<body>
	<h3>admin login</h3>
	<form method="POST">
		
		{% csrf_token %}
		<h4 style="color: red;">{{error}}</h4>
		{{form.as_p}}
		<button>login</button>
	</form>

</body>
</html>

templates/admintemplates/adminmessagedetail.html
{% extends 'admintemplates/base.html' %}


{% block content %}

<h3>{{message.name}}</h3>
<p>Date: {{message.date}}</p>
<h4>{{message.subject}}</h4>
<h4>{{message.email}}</h4>
<h4>{{message.message}}</h4>

{% endblock %}

templates/admintemplates/adminmessagelist.html
{% extends 'admintemplates/base.html' %}


{% block content %}
<style>
table {
    border-collapse: collapse;
    width: 100%;
}

th, td {
    text-align: left;
    padding: 8px;
}

tr:nth-child(even){background-color: #f2f2f2}

th {
    background-color: #4CAF50;
    color: white;
}
</style>
</head>
<body>


<table>
  <tr>
    <th>SN</th>
    <th>name</th>
    <th>content</th>
    <th>date</th>
  </tr>
  {% for a in messagelist %}
  <tr>
    <td>{{forloop.counter}}</td>
    <td><a href="{% url 'blogapp:adminmessagedetail' a.id %}">{{a.name}}</a></td>
    <td><a href="{% url 'blogapp:adminmessagedetail' a.id %}">{{a.message|truncatechars:'30'}}</a></td>
    <td>{{a.date|date}}</td>
  </tr>
  {% endfor %}
  
</table>


{% endblock %}

templates/admintemplates/adminnoticecreate.html
{% extends 'admintemplates/base.html' %}




{% block content %}

<form method="POST" enctype="multipart/form-data">
	{% csrf_token %}
	{{form.as_p}}
	<button>Submit</button>
	
</form>


{% endblock %}

templates/admintemplates/adminnoticedelete.html
{% extends 'base.html' %}


{% block content %}
<form method = "POST">
	{% csrf_token %}
	<button> Confirm Delete ?</button>
</form>
<a href="/">Cancel</a>



{%endblock%}

templates/admintemplates/adminnoticelist.html
{% extends 'admintemplates/base.html' %}

{% block content %}
<style>
table {
    border-collapse: collapse;
    width: 100%;
}

th, td {
    text-align: left;
    padding: 8px;
}

tr:nth-child(even){background-color: #f2f2f2}

th {
    background-color: #4CAF50;
    color: white;
}
</style>
</head>
<body>

<h2>Notice <a href="{% url 'blogapp:adminnoticecreate' %}"> Create New Notice</a></h2>

<table>
  <tr>
    <th>SN</th>
    <th>title</th>
    <th>content</th>
    <th>date</th>
  </tr>
  {% for a in noticelist %}
  <tr>
    <td>{{forloop.counter}}</td>
    <td>{{a.title}}</td>
    <td>{{a.content|truncatechars:'30'}}</td>
    <td>{{a.date|date}}</td>
  </tr>
  {% endfor %}
  
</table>
{% endblock %}

templates/admintemplates/base.html
<!DOCTYPE html>
<html>
<head>
	<title></title>
	<link rel="stylesheet" type="text/css" href="https://stackpath.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
</head>
<body class="container">
	{% if request.user.is_authenticated %}
	<h5>{{request.user.username}}</h5>
	<a href="{% url 'blogapp:adminlogout' %}">Logout</a>
	{% else %}

	<a href="{% url 'blogapp:adminlogin' %}">Login</a>
	{% endif %}

	<div class="row">
		<div class="col-md-3">
			<h3>sidebar</h3>
			<ul>
				<li><a href="{% url 'blogapp:adminhome' %}">HOME</a></li>
				<li><a href="{% url 'blogapp:adminbloglist' %}">BLOGS</a></li>
				<li><a href="{% url 'blogapp:adminnoticelist' %}">NOTICES</a></li>
				<li><a href="{% url 'blogapp:adminmessagelist' %}">MESSAGES</a></li>
				<li><a href="{% url 'blogapp:adminbooklist' %}">BOOKS</a></li>
				<li><a href="{% url 'blogapp:admincategorylist' %}">Category</a></li>
			</ul>
		</div>
		<div class="col-md-9">
			<h3>Content</h3>
			{% block content %}

			{% endblock %}
		</div>
	</div>



</body>
</html>